### PR TITLE
Add avatar image to readme, update dependencies

### LINKED ISSUE #1: Link to avatar image in readme is broken

### PR DESCRIPTION
**Pull request by ad-si**
Fixes #1

### CODE REVIEW

**Comment by ad-si** [comment]
@myroslambda ping

**Comment by myroslambda** [comment]
Thanks :) This patch does several things (some of which are not included in the issue), so I'll merge it manually.

**Comment by myroslambda** [comment]
So, just to explain what happened:

- We normally document all changes by creating one issue for each problem (dependencies, instructions, etc.). We commit each change independently, based on that.

- We don't really use stack. Cabal works well, and that's simple enough. Stack instructions have not been added.

- Because this is available on hackage, it's not necessary to install from the repo. People who know how to work with git know they can install directly by cloning. Otherwise, a simple `cabal update` and `cabal install avatar-generator` should do.

Thanks for the commit, @ad-si !

**Comment by ad-si** [comment]
Sounds good. You still should remove all the trailing whitespace though (and configure your editor / ide to do it automatically) 😉

**Pull request closed without merging**
